# Generated by Django 5.1.2 on 2024-11-12 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_invoice_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='tutor',
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
