# Generated by Django 5.1.2 on 2024-11-16 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_remove_lesson_location_remove_lesson_tutor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='notes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tutor',
            field=models.CharField(default='Unknown Tutor', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
