# Generated by Django 5.1.2 on 2024-11-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
