# Generated by Django 5.1.2 on 2024-11-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
