# Generated by Django 5.1.2 on 2024-11-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_lesson_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='notes',
        ),
    ]
