# Generated by Django 5.1.2 on 2024-11-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_user_is_tutor'),
        ('tutorials', '0013_lesson_notes'),
    ]

    operations = [
    ]
