# Generated by Django 5.1.2 on 2024-11-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_merge_0011_user_is_tutor_0013_lesson_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(),
        ),
    ]
