# Generated by Django 5.1.2 on 2024-11-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0015_alter_user_is_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_tutor',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('tutor', 'Tutor'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
