# Generated by Django 5.1.2 on 2024-11-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0017_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
