# Generated by Django 5.1.2 on 2024-12-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0019_alter_lesson_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Scala', 'Scala'), ('Web Development', 'Web Development')], max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='tutorials.subject'),
        ),
    ]
