# Generated by Django 5.1.2 on 2024-12-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0020_subject_user_subjects'),
        ('tutorials', '0020_tutorrequest'),
    ]

    operations = [
    ]
