# Generated by Django 5.1.2 on 2024-12-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0024_tutorrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='notes',
        ),
        migrations.DeleteModel(
            name='tutorRequest',
        ),
    ]
