# Generated by Django 5.1.2 on 2024-12-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0026_invoice_lesson_lesson_recurrence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Scala', 'Scala'), ('Web Development', 'Web Development')], max_length=50),
        ),
    ]
