# Generated by Django 5.1.2 on 2024-12-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0028_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='issued_date',
        ),
    ]
