# Generated by Django 5.1.2 on 2024-12-07 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0030_alter_lesson_duration_alter_lesson_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
