# Generated by Django 5.1.2 on 2024-12-08 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0031_alter_lesson_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
