# Generated by Django 5.1.2 on 2024-12-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0034_alter_invoice_student_alter_lesson_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
