# Generated by Django 5.1.2 on 2024-12-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0035_lesson_lesson_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_dates',
        ),
    ]
