# Generated by Django 5.1.2 on 2024-12-10 14:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0036_remove_lesson_lesson_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lesson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tutorials.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='recurrence_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
